/*Q2 calculate the area of a circle and modify the same program to calculate
the volumne of a cylindere gives its radius and height.*/
//ans(i)
# include<stdio.h>
int main()
{
    int r;
    printf("Enter the radius of a circle \n");
    scanf("%d",&r);
    printf("The area of a circle is :%f",3.14*r*r);
    return 0;
}
//ans(ii)
/*# include<stdio.h>
int main()
{
    int r,h;
    printf("Enter the radius of a cylinder \n");
    scanf("%d",&r);
    printf("Enter the height of a cylinder \n");
    scanf("%d",&h);
    printf("The volumne of a cylinder is %f\n",3.14*r*r*h);
    return 0;
} */